#pragma checksum "..\..\..\..\Scenes\Scene3.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "00CA09FA201D42AC7694175F45E59546109B6BB0"
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Vytah.Scenes {
    
    
    /// <summary>
    /// Scene3
    /// </summary>
    public partial class Scene3 : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image BgImage;
        
        #line default
        #line hidden
        
        
        #line 8 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitObraz1;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitTV;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitKomoda;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitMuz;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitDvere;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border KeypadOverlay;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\Scenes\Scene3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CodeInput;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Vytah;component/scenes/scene3.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Scenes\Scene3.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BgImage = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.HitObraz1 = ((System.Windows.Controls.Border)(target));
            
            #line 14 "..\..\..\..\Scenes\Scene3.xaml"
            this.HitObraz1.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitObraz1_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.HitTV = ((System.Windows.Controls.Border)(target));
            
            #line 23 "..\..\..\..\Scenes\Scene3.xaml"
            this.HitTV.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitTV_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.HitKomoda = ((System.Windows.Controls.Border)(target));
            
            #line 32 "..\..\..\..\Scenes\Scene3.xaml"
            this.HitKomoda.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitKomoda_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.HitMuz = ((System.Windows.Controls.Border)(target));
            
            #line 41 "..\..\..\..\Scenes\Scene3.xaml"
            this.HitMuz.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitMuz_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.HitDvere = ((System.Windows.Controls.Border)(target));
            
            #line 50 "..\..\..\..\Scenes\Scene3.xaml"
            this.HitDvere.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitDvere_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.KeypadOverlay = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.CodeInput = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            
            #line 71 "..\..\..\..\Scenes\Scene3.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ConfirmCode_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 74 "..\..\..\..\Scenes\Scene3.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelCode_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

