#pragma checksum "..\..\..\..\Scenes\Scene4.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1D5502F9AED3C6612DC6511F201C2DABF843B5A5"
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Vytah.Scenes {
    
    
    /// <summary>
    /// Scene4
    /// </summary>
    public partial class Scene4 : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image BgImage;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PaniLabel;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitPopel;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitAlarm;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HitRozvod;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FusePuzzle;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Slot1;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Slot2;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Slot3;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\Scenes\Scene4.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PuzzleStatus;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Vytah;component/scenes/scene4.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Scenes\Scene4.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BgImage = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.PaniLabel = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.HitPopel = ((System.Windows.Controls.Border)(target));
            
            #line 30 "..\..\..\..\Scenes\Scene4.xaml"
            this.HitPopel.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitPopel_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.HitAlarm = ((System.Windows.Controls.Border)(target));
            
            #line 42 "..\..\..\..\Scenes\Scene4.xaml"
            this.HitAlarm.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitAlarm_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.HitRozvod = ((System.Windows.Controls.Border)(target));
            
            #line 54 "..\..\..\..\Scenes\Scene4.xaml"
            this.HitRozvod.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HitRozvod_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.FusePuzzle = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.Slot1 = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\..\Scenes\Scene4.xaml"
            this.Slot1.Click += new System.Windows.RoutedEventHandler(this.SlotButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.Slot2 = ((System.Windows.Controls.Button)(target));
            
            #line 97 "..\..\..\..\Scenes\Scene4.xaml"
            this.Slot2.Click += new System.Windows.RoutedEventHandler(this.SlotButton_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Slot3 = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\Scenes\Scene4.xaml"
            this.Slot3.Click += new System.Windows.RoutedEventHandler(this.SlotButton_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.PuzzleStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            
            #line 114 "..\..\..\..\Scenes\Scene4.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OdeslitPuzzle_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 117 "..\..\..\..\Scenes\Scene4.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelPuzzle_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

